---
- hosts: raspbian
  become: true
  become_user: root
  tasks:
    - name: Install mandatory packages
      ansible.builtin.apt:
        name: "{{ (mandatory_packages + (packages | default([]))) | unique }}"
        state: present
        update_cache: yes

    - name: Install Docker packages
      ansible.builtin.apt:
        name: "{{ docker_packages }}"
        state: "{{ 'present' if docker_packages_required | default(true) else 'absent' }}"
        update_cache: yes

    - name: Reboot system if necessary
      reboot:
        msg: "Post setup reboot"
        connect_timeout: 5
        reboot_timeout: 120
        pre_reboot_delay: 0
        post_reboot_delay: 0
        test_command: uptime
      when: post_setup_reboot_required
